export const ERRORS = {
  EMAIL: "Please enter a valid Email",
  PASSWORD: "Please enter a valid Password",
  NAME: "Please enter a valid Name",
  LAST_NAME: "Please enter a valid Last name",
  CONTACT: "Please enter a valid Contact",
  ADDRESS: "Please enter a valid Address",
  FAILURE: "Error occured while saving record!",
  PRICE: "Please enter a valid price",
  TYPE: "Please enter a valid battery type",
  SERIAL_NO: "Please enter a valid serial number",
  GST: "Please enter a valid GST",
  AMPHERE: "Please select a valid AMPHERE",
  BATTERY: "Please select a valid BATTERY",
  P_CODE: "Please enter a valid Product code",
  SUCCESS: "Record added or updated successfully",
  DUPLICATE: "Contact number is already exists!",
  SERIAL_NUMBER: "Serial number and QTY did not match",
};
